### ISSUE TITLE
pycondor monitor may be broken

### ISSUE THREAD

**Issue by eagoetz** [pycondor/pycondor#158]
#### Description

The `pycondor monitor` process may have a bug in it because trying to use it to monitor a dag results in a traceback error.

#### Steps/code to reproduce issue
I think just running a dag and using the `monitor` option may be sufficient to trigger this error.

#### Expected results

This should just monitor the dag process without throwing an error

#### Actual results

```
$ /home/detchar/.conda/envs/ligo-summary-3.10/bin/pycondor monitor --time 10 /home/detchar/public_html/summary/gw_daily_summary_rerun.dag
Traceback (most recent call last):
  File "/home/detchar/.conda/envs/ligo-summary-3.10/bin/pycondor", line 10, in <module>
    sys.exit(cli())
  File "/home/detchar/.conda/envs/ligo-summary-3.10/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/detchar/.conda/envs/ligo-summary-3.10/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/detchar/.conda/envs/ligo-summary-3.10/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/detchar/.conda/envs/ligo-summary-3.10/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/detchar/.conda/envs/ligo-summary-3.10/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/detchar/.conda/envs/ligo-summary-3.10/lib/python3.10/site-packages/pycondor/cli.py", line 187, in monitor
    for status, datetime_current in status_generator(dag_out_file):
  File "/home/detchar/.conda/envs/ligo-summary-3.10/lib/python3.10/site-packages/pycondor/cli.py", line 76, in status_generator
    status = Status(*node_counts)
TypeError: Status.__new__() takes 8 positional arguments but 9 were given
```

**Comment by GregoryAshton** [comment]
Hi @eagoetz. I'm sorry, but these aspects o `pycondor` are not something I am familiar with either (we don't use the monitor at all). Can you just use `htcondor` operations instead?
